# Configuración de PostgreSQL
spring.datasource.url=postgresql://tutorconecta_db_user:ez1K1kuCx7GXtoNcOeGZOlZXU6GSCZhu@dpg-dap21dtg1s2s7394hu10-a/tutorconecta_db
spring.datasource.username=tutorconecta_db_user
spring.datasource.password=ez1K1kuCx7GXtoNcOeGZOlZXU6GSCZhu

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

jwt.secret=${Ys/+9BLSQIC/gwv2LPZYOV3x2ld2aVTslb9+oHQV7Eg=}